version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: event_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 10s
    ports:
      - "3307:3306"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8071:8071"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071

  event-service:
    build: ./event-service
    container_name: event-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/event_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - event-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/event_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - user-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/